name: Chatbot image

on:
  push:
    branches: ["main"]
    paths:
      - chat_bot/**
  pull_request:
    branches: ["main"]
    paths:
      - chat_bot/**
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: tom333:cv-chatbot

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: chat_bot/.
          push: true
          tags: ghcr.io/tom333/cv-chatbot:latest
          labels: ${{ steps.meta.outputs.labels }}